GET http://localhost:3001/auth/test

###

POST http://localhost:3001/auth/signup
Content-Type: application/json

{
    "login": "podpivasnik2281",
    "password": "sliva",
    "firstName": "Artem",
    "lastName": "Mironov"
}

###

POST http://localhost:3001/auth/signin
Content-Type: application/json

{
    "login": "podpivasnik228",
    "password": "sliva"
}

###

POST http://localhost:3001/tasks/newTask
Content-Type: application/json
Authorization: 5f68b1d468a7638212b65cef

{
    "text": "My first task",
    "checked": false
}

###

GET http://localhost:3001/tasks/
Authorization: 5f68b1d468a7638212b65cef

###

DELETE http://localhost:3001/tasks/5f69e1206125ce92e3335ae3
Authorization: 5f68b1d468a7638212b65cef

###

PATCH http://localhost:3001/tasks/5f69fdf84c18a5af2b81e4a3
Authorization: 5f68b1d468a7638212b65cef

{
    "checked": true
}

###

GET http://localhost:3001/auth/5f68b1d468a7638212b65cef