GET http://localhost:3000/products/2

###

POST http://localhost:3000/add
Content-Type: application/json

{
    "title": "test",
    "id": 5

}

###

GET http://localhost:3000/auth/test

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "login": "podpivasnik2281",
    "password": "sliva",
    "firstName": "Artem",
    "lastName": "Mironov"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "login": "podpivasnik228",
    "password": "sliva"
}